---
- name: install mysql-server package
  package:
    name: mysql-server
    state: present
  tags:
    - flask_db

- name: configure mysql bind-address
  lineinfile:
    dest: /etc/mysql/my.cnf
    regexp: '^bind-address'
    line: bind-address		= 0.0.0.0
  notify: restart mysql 
  tags:
    - flask_db

- name: get the mysql dump
  get_url:
    url: https://raw.githubusercontent.com/pstauffer/flask-mysql-app/master/students.sql 
    dest: /tmp/students.sql
    owner: root
    group: root
    mode: 0640
  tags:
    - flask_db

- name: load mysql dump
  shell: mysql --user=root --password='' < /tmp/students.sql
  changed_when: false
  ignore_errors: true
  tags:
    - flask_db

- name: start and enable mysql
  service:
    name: mysql
    state: started
    enabled: yes
  tags:
    - flask_db
